### ISSUE TITLE
loop only returns 6 products 

### ISSUE THREAD

**Issue by davidhodge931** [davidhodge931/vape-scrape#6]
<img width="478" alt="image" src="https://github.com/user-attachments/assets/64e68a5f-2221-4656-a4a2-6760dc0d2940">

**Comment by skittogh** [comment]
you can change the url filter lines 31-33 here. if you want to run the whole lot, it is a LONG loop, so you probably would only want to do it overnight or on a scheduler:
![image](https://github.com/user-attachments/assets/44875382-537d-4852-95a9-a957f9dd11c0)

**Comment by davidhodge931** [comment]
Oh whoops, thanks!

**Comment by skittogh** [comment]
sweet. might be worth looking into doing something like this to run the code. might not even need whitelisted domains on rstudio server if it can be run this way. https://www.youtube.com/watch?v=u-TcADhWosA
